### ISSUE TITLE
remove Firefox checker 

### ISSUE THREAD

**Issue by wjt** [flathub-infra/flatpak-external-data-checker#113]
I believe this is now unused. The Firefox package on Flathub is submitted directly from Mozilla's build process. The Endless flatpak which used to use this checker has been retired. The maintainer of the Thunderbird package has said they don't want to make use of an adapted version of the Firefox checker: https://github.com/flathub/org.mozilla.Thunderbird/issues/116

So, we can remove the Firefox checker, and possibly also the support for checking entire modules at a time (rather than individual sources) which was added for this checker.

**Comment by gasinvein** [comment]
~~Hmm. Firefox checker is the only one using the module checking logic. I think we should either remove the logic as well (unless we need it for something else, e.g. Rust checker probably could use it), or add other means to autotest it, otherwise we'll get a bunch of stale code.~~
Sorry, didn't read carefully, you literally wrote about the same thing.
