### ISSUE TITLE
Attempt to downgrade libportal

### ISSUE THREAD

**Issue by mcatanzaro** [flathub-infra/flatpak-external-data-checker#318]
In https://github.com/flathub/org.gnome.Epiphany/pull/39, flatpak-external-data-checker attempted to downgrade libportal from 0.6 to 0.5. That's not great.

**Comment by gasinvein** [comment]
This started to happen last year with GitHub's `.../releases/latest` API endpoint from time to time - it appears that it can suddenly return a previous release. I can't say that with certainty since I never managed to reproduce this locally.

In order to properly prevent downgrades, I suppose we'll need to keep track of the current version (e.g. by storing it in another `x-` prefixed property in the manifest) instead of blindly accepting whatever remote data we get.

**Comment by dreua** [comment]
Instance of #286

**Comment by dreua** [comment]
Can we close this as duplicate?

**Comment by mcatanzaro** [comment]
Duplicate of #286
