### ISSUE TITLE
Script requests to update to an older version

### ISSUE THREAD

**Issue by gpoo** [flathub-infra/flatpak-external-data-checker#338]
In https://github.com/flathub/org.gnome.Evince/pull/110 the script is recommending to downgrade, which is odd unless there is something I am missing.

```
Update libgxps-0.3.2.tar.xz to 0.2.5
```

0.3.2 archive was uploaded on 2021-02-26 whereas 0.2.5 on 2017-02-25

* https://download.gnome.org/sources/libgxps/0.3/
* https://download.gnome.org/sources/libgxps/0.2/

**Comment by dreua** [comment]
Wow, this is am extreme instance of #286

**Comment by ManuelHu** [comment]
The reason is simple:

https://github.com/flathub/flatpak-external-data-checker/blob/890dd4b8d6fca69539ccdc5c53727f55716877fc/src/checkers/gnomechecker.py#L32-L36

in this case, `major` is `0 <  41`, and `3 % 2 != 0`, so the relases `0.3.x` of libgxps are considered pre-releases. Only 0.2.x is seen after filtering, leading to the proposal of the downgrade.

I am not sure about the old gnome versioning policy, but maybe this should not happen for `major==0`?

**Comment by hadess** [comment]
> I am not sure about the old gnome versioning policy, but maybe this should not happen for `major==0`?

major == 0 is unlikely to realistically be used building Flatpaks, we'd be talking about software released 25 years ago, so that sounds reasonable to me.

Either that, or an `odd-even`, `odd-unstable` attribute that could be more generally used with a reference to: https://en.wikipedia.org/wiki/Software_versioning#Modifications_to_the_numeric_system

**Comment by gasinvein** [comment]
> major == 0 is unlikely to realistically be used building Flatpaks

Well, GNOME Photos uses `rest` library, which has major == 0 (see #358)

**Comment by hadess** [comment]
> Well, GNOME Photos uses `rest` library, which has major == 0 (see #358)

Please don't truncate my comments for them to mean something else. There aren't any `0.` prefixed modules that could be in use today that use the GNOME numbering scheme (2.x, 3.x, 40.x, etc.), as I mentioned.

There's still the problem of whether those modules use even-odd for stable-unstable releases, so an attribute would still be necessary.

**Comment by gasinvein** [comment]
I must be misunderstanding, then. Do you mean we can assume that projects with versions `0.` don't use the Gnome versioning scheme at all?

**Comment by hadess** [comment]
> I must be misunderstanding, then. Do you mean we can assume that projects with versions `0.` don't use the Gnome versioning scheme at all?

Exactly. Which means that we don't know whether they use odd-even or not. So we need an attribute for it.
