### ISSUE TITLE
flathubbot spams PR requests for the same update

### ISSUE THREAD

**Issue by ghisvail** [flathub-infra/flatpak-external-data-checker#400]
One a day for the last 2 weeks [here](https://github.com/flathub/org.raspberrypi.rpi-imager/pulls).

The release monitoring pattern should also be updated to discard the `rpios` suffix on the version tag.

Nonetheless, only a single PR should have been opened by the bot.

**Comment by wjt** [comment]
If you look closely the PR is different every day: it uses today's date for the release date.

This is because release-monitoring/anitya's API doesn't give us a release date, and https://github.com/raspberrypi/rpi-imager/archive/refs/tags/v1.8.3_rpios.tar.gz does not have a `Last-Modified`, so we use the `Date` header, which is always today's date.

I'll send you a PR to use a different checker.

**Comment by wjt** [comment]
The reason the date being different every day matters is that the name of the branch in the PR is derived from the contents of the Git tree, which is how the checker avoids opening multiple identical PRs. It keeps no state. I am beginning to doubt this design but that's how it works today.
