### ISSUE TITLE
RFE: Add the module name in the Github PR for updates

### ISSUE THREAD

**Issue by Justinzobel** [flathub-infra/flatpak-external-data-checker#405]
I'd really love to see the module name in FEDC PRs. Saves a click. Example https://github.com/flathub/org.kde.krdc/pull/48 just says `Update 2.11.2.tar.gz to 3.0.0` which isn't overly informative.

If it's just one module, it would be in the title of the MR.
If it's multiply it could just be done like so:
```
SomeModule: Update from 2.11.2 to 3.0.0
SomeOtherModule: Update from 2.11.2 to 3.0.0
```

**Comment by bbhtt** [comment]
This is because you are using plain tags, the filename of the tag does not have the name of the source.

The update message includes the filename

https://github.com/flathub/flatpak-external-data-checker/blob/b9b5770e480624e9d7adbab1176d89d94cd1d573/src/manifest.py#L454-L456

If you switch it to https://github.com/FreeRDP/FreeRDP/releases/download/2.11.4/freerdp-2.11.4.tar.gz, it'll include the name in the title.

> If it's multiply it could just be done like so

This would make the title unnecessarily verbose when there are many modules needing updates, the details are included in the commit message and PR description.

**Comment by wjt** [comment]
It's true that in other cases the tarball name gives a better message but I do agree that there is scope for improving the commit message(s) and/or PR message. Patches welcome!

I actually think the case where 2+ sources change is more of a problem because the message becomes "Update 2 modules". Maybe you can find a way to improve that, e.g. if all changed sources belong to the same module, name the module; or highlight the main source; etc.

**Comment by gasinvein** [comment]
This should be rather easy to implement, given that we know which module the updated source is associated with.

> the case where 2+ sources change is more of a problem because the message becomes "Update 2 modules". Maybe you can find a way to improve that

Maybe list all updated module (not source!) names in the title? E.g.
```
Update freerdp, krb5, pkcs11-helper

freerdp: Update 2.11.2.tar.gz to 3.0.0
krb5: Update krb5-1.21.1.tar.gz to 1.21.1
pkcs11-helper: Update pkcs11-helper-1.29.0.tar.gz to 1.29.0
```

**Comment by Justinzobel** [comment]
> This should be rather easy to implement, given that we know which module the updated source is associated with.
> 
> > the case where 2+ sources change is more of a problem because the message becomes "Update 2 modules". Maybe you can find a way to improve that
> 
> Maybe list all updated module (not source!) names in the title? E.g.
> 
> ```
> Update freerdp, krb5, pkcs11-helper
> 
> freerdp: Update 2.11.2.tar.gz to 3.0.0
> krb5: Update krb5-1.21.1.tar.gz to 1.21.1
> pkcs11-helper: Update pkcs11-helper-1.29.0.tar.gz to 1.29.0
> ```

Yes this would be ideal!

**Comment by bbhtt** [comment]
Shpuld be fixed by https://github.com/flathub-infra/flatpak-external-data-checker/pull/428 and https://github.com/flathub-infra/flatpak-external-data-checker/pull/429
